language: rust
rust:
  - nightly
os:
  - linux
  - osx
dist: trusty
sudo: required

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
    - zlib1g-dev
    - gettext
    - autopoint
    - texinfo

before_install: .travis/before_install.sh

script: .travis/script.sh

after_success: .travis/after_success.sh

notifications:
  email: false
